routes.py
from flask import Flask, render_template, request, flash, session, redirect, url_for, Blueprint

from forms import SignupForm, SigninForm, addmoneyForm, editprofileForm, unloadmoneyForm, billers_SigninForm, billers_SignupForm, paybillForm, adminsignForm

#from flask.ext.mail import Message, Mail

from models import db, wallet, billers, admin

blueprint1= Blueprint('simple_page', __name__,
                        template_folder='templates')


@blueprint1.route('/', methods = ['GET', 'POST'])
def index():
    if request.method == 'POST':
        return render_template('index.html')
    else:
        return render_template('index.html')


@blueprint1.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = SignupForm()

    #if 'email' in session:
        #return redirect(url_for('simple_page.profile'))

    if request.method == 'POST':
        if form.validate() == False:
            return render_template('signup.html', form = form)
        else:
            newuser = wallet(form.username.data, form.password.data, form.email.data ) #form.company.data
            db.session.add(newuser)
            db.session.commit()

            session['email'] = newuser.email

            return redirect(url_for('simple_page.profile'))

    elif request.method == 'GET':
        return render_template('signup.html', form = form)


@blueprint1.route('/profile')
def profile():
    print("hello")
    if 'email' not in session:
        return redirect(url_for('simple_page.signin'))

    user = wallet.query.filter_by(email=session['email']).first()

    if user is None:
        return redirect(url_for('simple_page.profile'))
    else:
        return render_template('profile.html', username = user.username, addmoney = user.money)


@blueprint1.route('/signin', methods=['GET', 'POST'])
def signin():
    form = SigninForm()

    if 'email' in session:
        return redirect(url_for('simple_page.profile'))

    if request.method == 'POST':
        if form.validate() == False:
            return render_template('signin.html', form=form)
        else:
            session['email'] = form.email.data
            return redirect(url_for('simple_page.profile'))

    elif request.method == 'GET':
        return render_template('signin.html', form=form)

@blueprint1.route('/signout')
def signout():

    if 'email' not in session:
        return redirect(url_for('simple_page.index'))

    session.pop('email', None)
    return redirect(url_for('simple_page.index'))


@blueprint1.route('/addmoney', methods=['GET', 'POST'])
def addmoney():
    form = addmoneyForm()

    if request.method == 'POST':
        if form.validate() == False:
            #print 'false'
            return render_template('addmoney.html', form=form)
        else:
            user = wallet.query.filter_by(email=session['email']).first()
            user.money += int(form.addmoney.data)
            print user.money
            db.session.add(user)
            db.session.commit()
        return render_template('addmoney.html', form=form, addmoney = user.money)
    return render_template('addmoney.html', form=form)


@blueprint1.route('/editprofile', methods=['GET', 'POST'])
def editprofile():
    form = editprofileForm()

    if request.method == 'POST':
        if form.validate() == False:
            return render_template('edit_profile.html', form=form)
        else:
            user = wallet.query.filter_by(email=session['email']).first()
            user.username = form.update_username.data
            user.password = form.update_password.data
            db.session.add(user)
            db.session.commit()
        return render_template('edit_profile.html', form = form, update_username = user.username, update_password = user.password)
    return render_template('edit_profile.html', form=form)


@blueprint1.route('/unloadmoney', methods=['GET', 'POST'])
def unloadmoney():
    form = unloadmoneyForm()

    if request.method == 'POST':
        if form.validate() == False:
            #print 'false'
            return render_template('unloadmoney.html', form=form)
        else:
            user = billers.query.filter_by(email=session['email']).first()
            user.money -= int(form.unloadmoney.data)
            print user.money
            db.session.add(user)
            db.session.commit()
        return render_template('unloadmoney.html', form=form, unloadmoney = user.money)
    return render_template('unloadmoney.html', form=form)


@blueprint1.route('/billers_signup', methods=['GET', 'POST'])
def billers_signup():
    form = billers_SignupForm()

    #if 'email' in session:
        #return redirect(url_for('simple_page.profile'))

    if request.method == 'POST':
        if form.validate() == False:
            return render_template('billers_signup.html', form = form)
        else:
            newuser = billers(form.username.data, form.password.data, form.email.data, form.category.data, form.commission.data ) #form.company.data
            db.session.add(newuser)
            db.session.commit()

            #session['email'] = newuser.email

            return redirect(url_for('simple_page.admin_profile'))

    elif request.method == 'GET':
        return render_template('billers_signup.html', form = form)


@blueprint1.route('/billers_signin', methods=['GET', 'POST'])
def billers_signin():
    form = billers_SigninForm()

    if 'email' in session:
        return redirect(url_for('simple_page.billers_profile'))

    if request.method == 'POST':
        if form.validate() == False:
            return render_template('billers_signin.html', form=form)
        else:
            session['email'] = form.email.data
            return redirect(url_for('simple_page.billers_profile'))

    elif request.method == 'GET':
        return render_template('billers_signin.html', form=form)


@blueprint1.route('/billersprofile')
def billers_profile():
    print("hello")
    if 'email' not in session:
        return redirect(url_for('simple_page.billers_profile'))

    user = billers.query.filter_by(email=session['email']).first()

    if user is None:
        return redirect(url_for('simple_page.billers_profile'))
    else:
        return render_template('billers_profile.html', username = user.username)


@blueprint1.route('/paybill', methods=['GET', 'POST'])
def paybill():
    form = paybillForm()

    if request.method == 'POST':
        if form.validate() == False:
            return render_template('paybill.html', form=form)
        else:
            user = wallet.query.filter_by(email=session['email']).first()
            user.money -= int(form.paymoney.data)
            print user.money
            db.session.add(user)
            db.session.commit()

            user1 = billers.query.filter_by(username=form.username.data).first()
            com = int(form.paymoney.data)*(int(user1.commission)/100.0)
            user1.money += int(form.paymoney.data)- int(com)
            db.session.add(user1)
            db.session.commit()

            user2 = admin.query.filter_by(username = "admin").first()
            user2.money += int(com)
            db.session.add(user2)
            db.session.commit()

        return render_template('paybill.html', form=form, paymoney = user.money, username = user.username)
    return render_template('paybill.html', form=form)


@blueprint1.route('/admin_signin', methods=['GET', 'POST'])
def admin_signin():
    form = adminsignForm()

    if 'email' in session:
        return redirect(url_for('simple_page.admin_profile'))

    if request.method == 'POST':
        if form.validate() == False:
            return render_template('admin_signin.html', form=form)
        else:
            session['email'] = form.email.data
            return redirect(url_for('simple_page.admin_profile'))

    elif request.method == 'GET':
        return render_template('admin_signin.html', form=form)


@blueprint1.route('/adminprofile')
def admin_profile():
    print("hello")
    if 'email' not in session:
        return redirect(url_for('simple_page.admin_signin'))

    user = admin.query.filter_by(email=session['email']).first()

    if user is None:
        return redirect(url_for('simple_page.admin_profile'))
    else:
        return render_template('admin_profile.html', username = user.username)

templates/addmoney.html
{% extends "layout.html" %}

{% block content %}
  <h2>Add money</h2>

  {% for message in form.addmoney.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

<form action="{{ url_for('simple_page.addmoney') }}" method=POST>



    <h3> Wallet Balance: {{ addmoney }} </h3>

    {{ form.hidden_tag() }}

    {{ form.addmoney.label }}
    {{ form.addmoney }}



    {{ form.submit }}
  </form>

{% endblock %}

templates/admin_profile.html
{% block content %}
  <li class="jumbo">
    <h2>Profile</h2>

<li><a href="{{ url_for('simple_page.admin_profile') }}">Admin Profile</a></li>
          <li><a href="{{ url_for('simple_page.signout') }}">Sign Out</a></li>
    <li></li><a href="{{ url_for('simple_page.unloadmoney') }}">Unload Money</a></li>
<li><a href="{{ url_for('simple_page.billers_signup') }}">Billers Sign-Up</a></li>

    <h3>This is {{ username }}</h3>
    <h3>This is {{ session['email'] }}'s profile page</h3>
  </div>
{% endblock %}

templates/admin_signin.html
{% block content %}
  <h2>Admin Sign In</h2>
 
  {% for message in form.email.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
   
  {% for message in form.password.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
   
  <form action="{{ url_for('simple_page.admin_signin') }}" method=POST>
    {{ form.hidden_tag() }}
     
    {{ form.email.label }}
    {{ form.email }}
     
    {{ form.password.label }}
    {{ form.password }}


     
    {{ form.submit }}
  </form>
     
    {% endblock %}

templates/billers_profile.html
{% block content %}
  <li class="jumbo">
    <h2>Profile</h2>

<li><a href="{{ url_for('simple_page.billers_profile') }}">Profile</a></li>
          <li><a href="{{ url_for('simple_page.signout') }}">Sign Out</a></li>
    <li></li><a href="{{ url_for('simple_page.unloadmoney') }}">Unload Money</a></li>

    <h3>This is {{ username }}</h3>
    <h3>This is {{ session['email'] }}'s profile page</h3>
  </div>
{% endblock %}

templates/billers_signin.html
 {% extends "layout.html" %}
{% block content %}
  <h2>Sign In</h2>
 
  {% for message in form.email.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
   
  {% for message in form.password.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
   
  <form action="{{ url_for('simple_page.billers_signin') }}" method=POST>
    {{ form.hidden_tag() }}
     
    {{ form.email.label }}
    {{ form.email }}
     
    {{ form.password.label }}
    {{ form.password }}
     
    {{ form.submit }}
  </form>
     
    {% endblock %}

templates/billers_signup.html
  {% block content %}
  <h2>Sign up</h2>
<li><a href="{{ url_for('simple_page.admin_profile') }}">Admin Profile</a></li>
          <li><a href="{{ url_for('simple_page.signout') }}">Sign Out</a></li>
  {% for message in form.username.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% for message in form.password.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% for message in form.email.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% for message in form.category.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% for message in form.commission.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}



  <form action="{{ url_for('simple_page.billers_signup') }}" method=POST>
    {{ form.hidden_tag() }}

    {{ form.username.label }}
    {{ form.username }}

      {{ form.password.label }}
    {{ form.password }}

    {{ form.email.label }}
    {{ form.email }}

    {{ form.category.label }}
    {{ form.category }}

      {{ form.commission.label }}
    {{ form.commission }}




    {{ form.submit }}
  </form>

{% endblock %}

templates/edit_profile.html
{% extends "layout.html" %}

{% block content %}
  <h2>Update Profile</h2>

  {% for message in form.update_username.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

{% for message in form.update_password.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

<form action="{{ url_for('simple_page.editprofile') }}" method=POST>

    <h3>This is Updated username {{ update_username }}</h3>
    <h3>This is Updated password {{ update_password }}</h3>


    {{ form.hidden_tag() }}

    {{ form.update_username.label }}
    {{ form.update_username }}

    {{ form.update_password.label }}
    {{ form.update_password }}


    {{ form.submit }}
  </form>

{% endblock %}

templates/index.html
{% block content %}
  <div class="jumbo">
    <h2>Home</h2>
<li><a href="{{ url_for('simple_page.signup') }}">User Sign Up</a></li>
          <li><a href="{{ url_for('simple_page.signin') }}">User Sign In</a></li>
      <br>
    <li><a href="{{ url_for('simple_page.billers_signin') }}">Billers Sign-In</a></li>
      <li><a href="{{ url_for('simple_page.admin_signin') }}">Admin Sign-In</a></li>

  </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Flask App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
  <body>

  <header>
    <div class="container">
      <h1 class="logo">Flask App</h1>
      <nav>
        <ul class="menu">

          {% if 'email' in session %}

          <li><a href="{{ url_for('simple_page.profile') }}">Profile</a></li>
          <li><a href="{{ url_for('simple_page.signout') }}">Sign Out</a></li>
          {% else %}
          <li><a href="{{ url_for('simple_page.signup') }}">Sign Up</a></li>
          <li><a href="{{ url_for('simple_page.signin') }}">Sign In</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>

templates/paybill.html
{% block content %}
  <h2>Pay Bill</h2>


    <div class="flash">{{ message }}</div>



<form action="{{ url_for('simple_page.paybill') }}" method=POST>

    <li><a href="{{ url_for('simple_page.profile') }}">Profile</a></li>
    <li><a href="{{ url_for('simple_page.signout') }}">Sign Out</a></li>



    <h3> Wallet Balance: {{ paymoney }} </h3>

    {{ form.hidden_tag() }}

     {{ form.paymoney.label }}
    {{ form.paymoney }}

     {{ form.username.label }}
    {{ form.username }}

    {{ form.submit }}
  </form>

{% endblock %}

templates/profile.html
{% block content %}
  <li class="jumbo">
    <h2>Profile</h2>
<li><a href="{{ url_for('simple_page.profile') }}">Profile</a></li>
          <li><a href="{{ url_for('simple_page.signout') }}">Sign Out</a></li>
    <li></li><a href="{{ url_for('simple_page.addmoney') }}">Add Money</a></li>
    <li><a href="{{ url_for('simple_page.editprofile') }}">Edit Profile</a></li>
    <h3>This is {{ username }}</h3>
    <h3>Wallet Balance {{ addmoney }}</h3>
    <li><a href="{{ url_for('simple_page.paybill') }}">Pay Bill</a></li>
    <h3>This is {{ session['email'] }}'s profile page</h3>
  </div>
{% endblock %}

templates/signin.html
 {% extends "layout.html" %}
{% block content %}
  <h2>Sign In</h2>
 
  {% for message in form.email.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
   
  {% for message in form.password.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
   
  <form action="{{ url_for('simple_page.signin') }}" method=post>
    {{ form.hidden_tag() }}
     
    {{ form.email.label }}
    {{ form.email }}
     
    {{ form.password.label }}
    {{ form.password }}
     
    {{ form.submit }}
  </form>
     
    {% endblock %}

templates/signup.html
{% extends "layout.html" %}
  {% block content %}
  <h2>Sign up</h2>

  {% for message in form.username.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% for message in form.password.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% for message in form.email.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}



  <form action="{{ url_for('simple_page.signup') }}" method=post>
    {{ form.hidden_tag() }}

    {{ form.username.label }}
    {{ form.username }}

      {{ form.password.label }}
    {{ form.password }}

    {{ form.email.label }}
    {{ form.email }}




    {{ form.submit }}
  </form>

{% endblock %}

templates/unloadmoney.html
{% block content %}
  <h2>Add money</h2>

  {% for message in form.unloadmoney.errors %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
<li><a href="{{ url_for('simple_page.billers_profile') }}">Billers Profile</a></li>

<form action="{{ url_for('simple_page.unloadmoney') }}" method=POST>
    <li><a href="{{ url_for('simple_page.signout') }}">Sign Out</a></li>



    <h3> Wallet Balance: {{ unloadmoney }} </h3>

    {{ form.hidden_tag() }}

    {{ form.unloadmoney.label }}
    {{ form.unloadmoney }}



    {{ form.submit }}
  </form>

{% endblock %}